# Generated by Django 4.1.2 on 2022-10-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte'), ('MS', 'Menor Sin Identificación'), ('AS', 'Adulto Sin Identificación'), ('NI', 'NIT'), ('NU', 'Número Único de Identificación'), ('OT', 'Otro')], max_length=2)),
                ('document_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=100)),
            ],
        ),
    ]
